Web/Controllers/ContasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Repository.Conta;
using RestSharp;
using Services.Account;
using Web.ViewModel;

namespace Web.Controllers
{
    public class ContasController : Controller
    {
        private IContaIdentityManager _contaIdentityManager;

        public ContasController(IContaIdentityManager contaIdentityManager)
        {
            _contaIdentityManager = contaIdentityManager;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Login(string returnUrl = "")
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl)
        {
            try
            {
                var result = await _contaIdentityManager.Login(model.Email, model.Password);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError(string.Empty, "Login ou Senha inválidos");
                    return View(model);
                }

                var client = new RestClient();
                var request = new RestRequest("https://localhost:44343/api/authenticate/token", DataFormat.Json);
                request.AddJsonBody(model);
                var response = client.Post<string>(request);
                HttpContext.Session.SetString("Token", response.Data);

                if (!String.IsNullOrWhiteSpace(returnUrl))
                {
                    return Redirect(returnUrl);
                }

                return Redirect("/");
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Ocorreu um erro, por favor tente mais tarde.");
                return View(model);
            }
        }

        public IActionResult Logout()
        {
            _contaIdentityManager.Logout();
            foreach (var cookie in HttpContext.Request.Cookies)
            {
                Response.Cookies.Delete(cookie.Key);
            }
            return Redirect("/Contas/Login");
        }
    }
}

Web/Views/Contas/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<h1>@ViewData["Title"]</h1>

@model Web.ViewModel.LoginViewModel

<div class="text-center">
    <h1 class="display-4">Login</h1>
</div>


<div asp-validation-summary="All" class="text-danger"></div>
<form asp-action="Login" asp-controller="Contas" method="post" asp-route-returnurl="@ViewBag.ReturnUrl">
    <div class="form-group">
        <label for="exampleInputEmail1">Email</label>
        <input type="email" asp-for="Email" class="form-control" placeholder="Enter email">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" asp-for="Password" class="form-control" placeholder="Enter Password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

<hr />